export const TagColor: Record<string, string> = {
  react: '#61DAF6',
  nextjs: '#000000',
  go: '#00ADD8',
  graphql: '#e535ab',
  reactnative: '#2D2D2D',
  redux: '#764ABC',
  node: '#68A063',
  javascript: '#F7DF1E',
  typescript: '#234A84',
  python: '#4B8BBE',
  docker: '#0db7ed',
  kubernetes: '#326ce5',
  babel: '#f5db53',
  android: '#56a036',
  ios: '#0c76e2',
  redis: '#D82C20',
  webpack: '#8dd6f9',
  aws: '#FF9900',
  gcp: '#4285F4',
  testing: '#049c64',
  devops: '#059f00',
};

export enum Stack {
  typescript = 'TypeScript',
  javascript = 'JavaScript',
  go = 'Go',
  react = 'React',
  reactnative = 'React Native',
  graphql = 'GraphQL',
  aws = 'AWS',
  kubernetes = 'Kubernetes',
  gcp = 'Google Cloud',
  python = 'Python',
  node = 'Node',
}

export enum WorkStack {
  typescript = 'TypeScript',
  go = 'Go',
  kubernetes = 'Kubernetes',
  react = 'React',
  reactnative = 'React Native',
  graphql = 'GraphQL',
  aws = 'AWS',
  gcp = 'Google Cloud',
}
