import 'tailwindcss/tailwind.css';

import '../styles/globals.scss';
import '../styles/list.scss';
import '../styles/bottomsheet.scss';

import type { AppProps } from 'next/app';
import Head from 'next/head';
import config from '../config';
import { ThemeProvider } from 'next-themes';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider defaultTheme='system' attribute='class'>
      <Head>
        <title>{config.personal.fullName}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

export default MyApp;
