import Head from 'next/head';
import Image from 'next/image';

import config from '../config';

import {
  SubHeader,
  Banner,
  Footer,
  List,
  ProjectCard,
  ArticleCard,
} from '../components';

import { Card, Row, Col } from 'antd';

export default function Home() {
  const [articles, setArticles] = useState<any>([]);

  useEffect(() => {
    fetchArticles();
  }, []);

  async function fetchArticles(): Promise<void> {
    fetch('https://dev.to/api/articles?username=karanpratapsingh')
      .then(response => response.json())
      .then(response => {
        setArticles(response);
      });
  }

  function renderProjectsList(project: Project): React.ReactNode {
    const { title, description, banner } = project;
    return <ProjectCard title={title} description={description} banner={banner} />;
  }

  function renderArticlesList(article: any): React.ReactNode {
    const { title, description, tag_list: tags } = article;
    return <ArticleCard title={title} description={description} tags={tags} />;
  }

  return (
    <div className='flex flex-col'>
      <Head>
        <title>{config.fullName}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Header />
        <Banner />
      </div>

      <div className='px-10 py-5'>
        <SubHeader
          title='Portfolio'
          description={`Projects I've worked on recently`}
        />
        <Row gutter={[8, 8]}>
          {projects.map(project => {
            return (
              <Col key={project.id} className='' sm={8} xxl={4}>
                <Card
                  hoverable
                  className='rounded'
                  cover={
                    <Image
                      src={project.banner}
                      height={240}
                      width={400}
                      objectFit='cover'
                      alt='card'
                    />
                  }
                >
                  <div className='flex flex-col p-6'>
                    <span className='text-lg font-bold'>{project.title}</span>
                    <p className='text-sm font-light line-clamp-2'>
                      {project.description}
                    </p>
                  </div>
                </Card>
              </Col>
            );
          })}
        </Row>
      </div>

      <List
        title='Portfolio'
        description={`Projects I've worked on recently`}
        data={projects}
        renderList={renderProjectsList}
      />

      <List
        title='Articles'
        description={`When I'm not writing code, I write articles`}
        data={articles}
        renderList={renderArticlesList}
      />

      <Footer />
    </div>
  );
}

import { PageHeader, Switch } from 'antd';
import projects, { Project } from '../config/projects';
import { useEffect, useState } from 'react';

function Header(): React.ReactElement {
  return (
    <PageHeader
      extra={<Switch checkedChildren={'🌙'} unCheckedChildren={'☀️'} />}
    />
  );
}
