import Head from 'next/head';
import Image from 'next/image';

import config from '../config';

import { SubHeader, Banner } from '../components';
import { Card, Row, Col, List, Avatar } from 'antd';

export default function Home() {
  return (
    <div className='flex flex-col'>
      <Head>
        <title>{config.fullName}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Header />
        <Banner />
      </div>

      <div className='p-10'>
        <SubHeader
          title='Portfolio'
          description={`Projects I've worked on recently`}
        />
        <Row gutter={[8, 8]}>
          {projects.map(project => {
            return (
              <Col key={project.id} className='' sm={8} xxl={4}>
                <Card
                  hoverable
                  className='rounded'
                  cover={
                    <Image
                      src={project.banner}
                      height={240}
                      width={400}
                      objectFit='cover'
                      alt="card" />
                  }
                >
                  <div className='flex flex-col'>
                    <span className='text-lg font-bold'>{project.title}</span>
                    <span className='text-sm font-light truncate text-ellipsis'>{project.description}</span>
                  </div>
                </Card>
              </Col>
            );
          })}
        </Row>
      </div>

    </div>
  );
}

import { PageHeader, Switch } from 'antd';
import projects from '../config/projects';

function Header(): React.ReactElement {
  return (
    <PageHeader
      extra={<Switch checkedChildren={'🌙'} unCheckedChildren={'☀️'} />}
    />
  );
}
